### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by rehui** [eiblog/eiblog#21]
2018/12/21 22:22:08.838152 [ERROR] mongo.go:29: no reachable servers
Func : github.com/eiblog/utils/mgo.init.0
File:/home/travis/gopath/pkg/mod/github.com/eiblog/utils@v0.0.0-20180209055746-a56f1b5e9c3c/mgo/mongo.go:29
Func :
File::0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x790efc]

goroutine 1 [running]:
gopkg.in/mgo%2ev2.(*Session).SetMode(0x0, 0x2, 0x1)
	/home/travis/gopath/pkg/mod/gopkg.in/mgo.v2@v2.0.0-20180705113604-9856a29383ce/session.go:1681 +0x2c
github.com/eiblog/utils/mgo.init.0()
	/home/travis/gopath/pkg/mod/github.com/eiblog/utils@v0.0.0-20180209055746-a56f1b5e9c3c/mgo/mongo.go:31 +0xa7

**Comment by deepzz0** [comment]
@rehui 需要指定 mongodb 的 host 地址：https://github.com/eiblog/eiblog/blob/master/docs/install.md#%E6%9C%AC%E5%9C%B0%E6%B5%8B%E8%AF%95
